### ISSUE TITLE
[omnidoc] Workspace root directory not found

### ISSUE THREAD

**Issue by noxify** [souporserious/omnidoc#173]
Hi,

maybe it's to early to report the issue, but upgraded to `omnidoc` and currently I get the following error:

```
[1]  ⨯ {
[1]   code: -32603,
[1]   message: '[omnidoc] Internal error for method "analyzeSourceText" with params: {"isInline":true,"value":"Button","language":"typescript"}',
[1]   data: '[omnidoc] Workspace root directory not found',
[1]   digest: '3768333748'
[1] }
```

Based on the error message `[omnidoc] Workspace root directory not found` I have searched for it in the repo and identified the function `getRootDirectory`.

I didn't spent a lot of time to analyze it, but it seems that the function requires/expects a workspace setup.

If I set `workspaces: {}` in the package.json, the error is gone. But without, it can't determine the project root and fails with the mentioned error.

Question:
* Is this the expected behavior and the current workaround with `workspaces: {}` is also the solution ( = means, it's required even when we do not have a workspace/monorepo?)
* Do you need more information?

**Comment by souporserious** [comment]
Whoops, forgot to check for non-monorepos 😄 thanks for the heads up! Should be fixed in the next release.
